name: GitHub Actions Secrets
run-name: ${{ github.actor }} is testing out GitHub Secrets
on: [push] # pull - merges - this is the action
jobs:
  Explore-GitHub-Secrets:
    runs-on: ubuntu-latest # this ubuntu container is running in github side.
    steps:
      - name: Echo secrets
        env: 
          MY_SECRET: ${{ secrets.TEST_SECRET}} #TEST_SECRET is the name of the secret
        run: echo "My secret is ${MY_SECRET}" # this is a shell command!

        